@startuml LocacaoCarros

entity documento{
    id <<PK>>
    id_pessoa <<FK>>
    numero
    tipo
    dt_emissao
    dt_validade
}

entity pessoa {
    id <<PK>>
    telefone
    endereco
    cidade
    email
}

entity pessoa_fisica {
    id_pessoa <<FK>>
    nome
    dt_nascimento
    genero
}

entity pessoa_juridica {
    id_pessoa <<FK>>
    nome_fantasia
    razao_social
    dt_abertura
}

entity motorista {
    id_pessoa_fisica <<FK>>
    id_pessoa <<FK>>
}

entity carro {
    id <<PK>>
    placa
    modelo
    ano
    cor
    km_rodados
    valor_diaria
    capacidade_tanque
    situacao
}

entity locacao {
    id <<PK>>
    id_carro <<FK>>
    id_motorista <<FK>>
    id_funcionario <<FK>>
    dt_locacao
    dt_devolucao
    valor_estimado
    valor_total
}

entity filial {
    id <<PK>>
    nome
    endereco
    cidade
    telefone
    email
    capacidade
}

entity funcionario {
    id_pessoa_fisica <<FK>>
    matricula
    data_admissao
    situacao
    cargo
    salario
}

entity filial_carro {
    id_filial <<FK>>
    id_carro <<FK>>
}

entity filial_documento {
    id_filial <<FK>>
    id_documento <<FK>>
}

entity seguro {
    id <<PK>>
    descricao
    valor
    dt_inicio
    dt_fim
}

entity carro_seguro {
    id_carro <<FK>>,
    id_seguro <<FK>>
}

carro_seguro -- seguro
carro_seguro -- carro

filial_carro -- filial
filial_carro -- carro

filial_documento -- filial
filial_documento -- documento

pessoa_fisica -- pessoa
pessoa_juridica -- pessoa

motorista -- pessoa
motorista -- pessoa_fisica

funcionario -- pessoa_fisica

locacao -- carro
locacao -- motorista
locacao -- funcionario

documento -- pessoa


@enduml
